# .github/workflows/main.yml
# This is the main CI/CD pipeline. Its only job is to build and test the code.
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Build and Tests
        run: |
          echo "Running build and test steps..."
          # To test the failure notification, uncomment the next line
          exit 1
          echo "All steps passed!"
