# .github/workflows/main.yml
# This is the main CI/CD pipeline. It now has a second job to publish logs on failure.
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Build and Tests
        run: |
          echo "Running build and test steps..."
          echo "This is a sample success message."
          echo "Simulating an error now..."
          # To test the failure notification, uncomment the next line
          exit 1
          echo "This line will not be reached."

  # This job ONLY runs if the build-and-test job fails.
  # Its sole purpose is to capture the logs and upload them as an artifact.
  publish-logs-on-failure:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: failure()
    permissions:
      actions: read # Permission to read logs from other jobs in the same run
    steps:
      - name: Fetch logs from failed job
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # This command gets the logs of the previously failed job in this same workflow run.
          gh run view ${{ github.run_id }} --log-failed > failure_logs.txt

      - name: Upload failure logs as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: failure-logs # The artifact will be named this.
          path: failure_logs.txt
          retention-days: 1 # We only need the logs for a short time.
