# .github/workflows/main.yml
# This is the main CI/CD pipeline. It contains multiple jobs.
# It does NOT handle notifications directly.
name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Build Steps
        run: |
          echo "Running build steps..."
          # This job will succeed
          echo "Build successful!"

  # This job depends on the 'build' job succeeding first.
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Tests
        run: |
          echo "Running unit tests..."
          echo "A test is about to fail..."
          # To test the failure notification, this command will cause an error
          cat non_existent_test_report.xml
