# .github/workflows/notify.yml
# This workflow is triggered ONLY after the main "CI/CD Pipeline" workflow completes.
name: Send Pipeline Notification

on:
    workflow_dispatch:
#   workflow_run:
#     workflows: ["CI/CD Pipeline"] # IMPORTANT: This MUST match the 'name' of the main workflow
#     types:
#       - completed

jobs:
  notify:
    runs-on: ubuntu-latest
    # This single job runs on any completion and branches logic internally
    permissions:
      actions: read # Still required to download artifacts from another workflow run.
    steps:
      - name: Handle Success
        if: github.event.workflow_run.conclusion == 'success'
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          PIPELINE_NAME: ${{ github.event.workflow_run.name }}
          PIPELINE_URL: ${{ github.event.workflow_run.html_url }}
          COMMIT_SHA: ${{ github.event.workflow_run.head_sha }}
          AUTHOR: ${{ github.event.workflow_run.actor.login }}
        run: |
          JSON_PAYLOAD=$(cat <<EOF
          {
            "type": "message",
            "attachments": [{"contentType": "application/vnd.microsoft.card.adaptive","content": {"type": "AdaptiveCard","version": "1.4","body": [{"type": "TextBlock","text": "CI/CD Pipeline Succeeded: ${PIPELINE_NAME}","weight": "Bolder", "size": "Large", "color": "Good"},{"type": "FactSet","facts": [{"title": "Status:", "value": "✅ Success"},{"title": "Author:", "value": "${AUTHOR}"},{"title": "Commit:", "value": "$(echo ${COMMIT_SHA} | cut -c1-7)"}]}],"actions": [{"type": "Action.OpenUrl", "title": "View Pipeline Run", "url": "${PIPELINE_URL}"}]}}]
          }
          EOF
          )
          curl -X POST -H "Content-Type: application/json" -d "$JSON_PAYLOAD" "$TEAMS_WEBHOOK_URL"

      - name: Handle Failure
        if: github.event.workflow_run.conclusion == 'failure'
        uses: actions/checkout@v4 # Checkout code to access the notify.py script

      - name: Setup Python for Failure Analysis
        if: github.event.workflow_run.conclusion == 'failure'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        if: github.event.workflow_run.conclusion == 'failure'
        run: pip install langchain langchain-google-genai requests

      - name: Download failure logs from artifact
        if: github.event.workflow_run.conclusion == 'failure'
        uses: actions/download-artifact@v4
        with:
          name: failure-logs # Must match the name from the upload step in main.yml
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }} # Explicitly provide the token to ensure correct permissions

      - name: Run Analysis and Send Notification
        if: github.event.workflow_run.conclusion == 'failure'
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
          PIPELINE_STATUS: "failure"
          PIPELINE_NAME: ${{ github.event.workflow_run.name }}
          PIPELINE_URL: ${{ github.event.workflow_run.html_url }}
          COMMIT_SHA: ${{ github.event.workflow_run.head_sha }}
          AUTHOR: ${{ github.event.workflow_run.actor.login }}
        run: |
          # The download-artifact action places the file (failure_logs.txt) in the current directory.
          # The python script will find it automatically.
          python notify.py
